### ISSUE TITLE
[BUG]: zenml deploy is broken for Azure with seemingly hard-coded admin password

### ISSUE THREAD

**Issue by fschlz** [zenml-io/zenml#1251]
### System Information

ZenML version: 0.30.0
Install path: /Users/fschulz/.pyenv/versions/3.10.8/lib/python3.10/site-packages/zenml
Python version: 3.10.8
Platform information: {'os': 'mac', 'mac_version': '13.1'}
Environment: native
Integrations: ['azure', 'github']

[installed-python-packages.txt](https://github.com/zenml-io/zenml/files/10487861/installed-python-packages.txt)

### What happened?

I setup a K8s cluster on Azure & configured kubectl to use it.
Then I ran `zenml deploy` as described, including setting an admin password.
I used one generated from my password manager, but I get an error (see L28 in the log output below) that another password `zWAzgYBnsULz` has been set. This is not the password I entered, however.
The deployment fails subsequently.

Here is the log file:
[zenml-deploy-destroy-error.log](https://github.com/zenml-io/zenml/files/10487799/zenml-deploy-destroy-error.log)

### Reproduction steps

I followed the advice on the website: https://docs.zenml.io/getting-started/deploying-zenml/cli#option-1-starting-from-scratch

1. setup Azure AKS
2. configure it in kubectl
3. run `zenml deploy`
4. choose Azure as cloud provider
5. enter admin credentials
6. watch it fail

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
@fschlz So sorry for that one - Your logs are very helpful. Let us assess this internally and we try to fix it asap.

In the meanwhile, you might want to just deploy manually using [Docker ](https://docs.zenml.io/getting-started/deploying-zenml/docker) or [Helm](https://docs.zenml.io/getting-started/deploying-zenml/helm). Hope thats good for a quick workaround!

**Comment by fschlz** [comment]
@htahir1 FYI
I tried it a bunch of times with different passwords that match the requirements, and it gives me the same error.
I also tried copy/pasting and typing it in directly. No change.

**Comment by wjayesh** [comment]
Hi @fschlz ! Thanks for reporting this issue; there is some confusion: the admin password isn't hardcoded but here's some more context. I've also [pushed a PR](https://github.com/zenml-io/zenml/pull/1252) to fix this.
The value that you type in for the admin password is the one that is used for your ZenML Server account and the error that we're seeing here is coming from the random password that this recipe generates for the MySQL instance running on Azure that powers this ZenML server.

Right now, the generation is random and may include/exclude numbers in the password which makes Azure complain if it doesn't exactly satisfy the criteria.

**Comment by fschlz** [comment]
> Right now, the generation is random and may include/exclude numbers in the password which makes Azure complain if it doesn't exactly satisfy the criteria.

Forgive me, but it doesn't seem to be random if I get the same password a few times in a row.

**Comment by wjayesh** [comment]
In terraform, if you run apply again and again, and if the resource in question doesn't require a change, terraform reuses the older value. My bad, I wasn't clear on the scope of `random` here. I meant that for each unique instance of a terraform deployment, the password will be different and random. If you do a destroy on your resources and run apply again, the password you see will be different.

**Comment by fschlz** [comment]
@wjayesh Good to know! However, I did run destroy commands, as you can see from the log file.
The resource group, for example, has been created in Azure, but nothing else.
So, I ran `zenml destroy` to tear that down. It returned the same error as `deploy`, however.

**Comment by wjayesh** [comment]
This is because running destroy also uses the older values to refresh the `state` before deleting resources. If possible, can you try running `terraform destroy` with the flag `refresh=False`? This functionality is not natively supported with the `zenml destroy` command but can be used to bypass any refreshing of the terraform state.
You'll have to run this command from the directory which hosts this recipe. You can find it in `~/.config/zen_server/terraform/` directory.

**Comment by fschlz** [comment]
@wjayesh `~/.config/zen_server/terraform/` doesn't seem to exist on my system.
Am I missing critical setup steps I should have taken here?

**Comment by htahir1** [comment]
@fschlz Maybe try ZenML 0.32.0 (The latest release). We just hot-fixed this problem moments before we released to help you out there. Maybe try zenml deploy again after upgrading?

**Comment by htahir1** [comment]
@fschlz Did that work out?

**Comment by fschlz** [comment]
@htahir1 Nope, still broken.

It seems a variable is not set in terraform.

```
Error: No value for required variable

  on variables.tf line 1:
   1: variable "server_id" {

The root module input variable "server_id" is not set, and has no default value. Use a -var or -var-file command line argument to provide a value for this variable.

TerraformCommandError: Command 'terraform apply -var-file=/var/folders/8w/q5n82czn0xs7sdkr87pv0_hm0000gn/T/tmp_f47ew9j.tfvars.json -no-color -input=false -auto-approve=false' returned non-zero exit status 1.
```

**Comment by wjayesh** [comment]
@fschlz We removed the `server_id` variable in 0.31.0; it feels like the recipe files are left over in your global config from a previous version. Can you try the following:

1. Go into `~/config/zenml/zen_server/terraform` and run 
```
terraform destroy -refresh=False
```
When it asks you to enter values for variables, input any random values.

2.  Once the resources are deprovisioned, delete the terraform directory. 
3. Now run `zenml deploy` again.

**Comment by fschlz** [comment]
@wjayesh So, I did that and now I seems to deploy, although I get a terraform warning

```
Apply complete! Resources: 11 added, 0 changed, 0 destroyed.

Outputs:

ca_crt = <sensitive>
password = <sensitive>
username = "default"
zenml_server_url = "https://IP-ADDRESS.nip.io/"
Your ZenML server is now deployed with URL:
https://IP-ADDRESS.nip.io/

WARNING:python_terraform:error: b''
```

The terraform warning is weird, because seemingly empty, but ok.

Then I ran `zenml connect --url https://IP-ADDRESS.nip.io/ --username=default --no-verify-ssl` with the ZenML server URL it gave me, which yields this error:

```
RuntimeError: Error initializing rest store with URL ...: HTTPSConnectionPool(host=..., port=443): Max retries exceeded with url: /api/v1/login (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x10b5820b0>, 'Connection to ... timed out. (connect timeout=30)'))
```

Is that not the right address to use with `zenml connect`?

**Comment by htahir1** [comment]
Maybe you dont need to do the `--no-verify-ssl`? Can you Slack us the IP-ADDRESS? Maybe it isnt deployed properly? There could be many reasons. You might want to debug the deployed server now: https://docs.zenml.io/getting-started/deploying-zenml/troubleshooting

**Comment by htahir1** [comment]
@fschlz Is it okay if I close this issue?
